create table if not exists public.lotto_draws (
  id bigint generated by default as identity primary key,
  main_numbers jsonb not null,
  bonus_number integer not null check (bonus_number between 1 and 45),
  drawn_at timestamptz not null default now()
);

alter table public.lotto_draws enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'lotto_draws'
      and policyname = 'allow read lotto draws'
  ) then
    create policy "allow read lotto draws"
    on public.lotto_draws
    for select
    to anon
    using (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'lotto_draws'
      and policyname = 'allow insert lotto draws'
  ) then
    create policy "allow insert lotto draws"
    on public.lotto_draws
    for insert
    to anon
    with check (true);
  end if;
end $$;

create index if not exists lotto_draws_drawn_at_idx
  on public.lotto_draws (drawn_at desc);
